apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: authentik-production-postgresql
      jsonPointers:
        - /data
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/applications/authentik
    helm:
      values: |
        authentik:
          authentik:
            secret_key: ""
            bootstrap:
              email: "brian@lab1830.com"
              password: ""
            postgresql:
              password: ""
            redis:
              password: ""
          global:
            env:
              - name: AUTHENTIK_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: authentik-secrets
                    key: secret-key
              - name: AUTHENTIK_BOOTSTRAP_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: authentik-secrets
                    key: bootstrap-password
              - name: AUTHENTIK_POSTGRESQL__PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: authentik-secrets
                    key: postgresql-password
          server:
            replicas: 1
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
              hosts:
                - auth.lab1830.com
              tls:
                - hosts:
                    - auth.lab1830.com
                  secretName: authentik-production-tls
          worker:
            replicas: 1
            volumes:
              - name: shm
                emptyDir:
                  medium: Memory
                  sizeLimit: 64Mi
            volumeMounts:
              - name: shm
                mountPath: /dev/shm
            startupProbe:
              failureThreshold: 120
              periodSeconds: 10
              timeoutSeconds: 30
              initialDelaySeconds: 60
            livenessProbe:
              timeoutSeconds: 30
              periodSeconds: 30
            readinessProbe:
              timeoutSeconds: 30
              periodSeconds: 30
          postgresql:
            enabled: true
            image:
              tag: "18"
            auth:
              username: authentik
              database: authentik
              existingSecret: authentik-secrets
              secretKeys:
                userPasswordKey: postgresql-password
            primary:
              persistence:
                storageClass: local-path
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
          redis:
            enabled: true
            image:
              tag: "8"
            auth:
              enabled: false
            master:
              persistence:
                storageClass: local-path
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik-production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
