apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/applications/descheduler
    helm:
      valueFiles:
        - values.yaml
        # No overrides - use production defaults
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true