apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etcd-monitor-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/infrastructure/etcd-monitor
    helm:
      values: |
        schedule: "0 */6 * * *"
        maxAgeHours: 24
        prometheusRule:
          enabled: true
          additionalLabels:
            release: monitoring-production
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
