apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/applications/homepage
    helm:
      valueFiles:
        - values.yaml
      values: |
        replicaCount: 2
        # Add environment variable for host validation
        env:
          - name: HOMEPAGE_ALLOWED_HOSTS
            value: "homepage.lab1830.com"
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: homepage.lab1830.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: homepage-tls-gitops
              hosts:
                - homepage.lab1830.com
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage-production
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
