apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/applications/kyverno
    helm:
      valueFiles:
        - values.yaml
      skipCrds: true
      values: |
        policy-reporter:
          ui:
            ingress:
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
              hosts:
                - host: kyverno.lab1830.com
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - hosts:
                    - kyverno.lab1830.com
                  secretName: kyverno-production-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jsonPointers:
        - /spec
