apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.35.1
    chart: loki
    helm:
      values: |
        # Single binary deployment for production
        deploymentMode: SingleBinary

        loki:
          # TODO: Consider enabling auth for multi-tenant or high-security environments
          # Requires updating Promtail and Grafana with credentials
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          limits_config:
            retention_period: 168h  # 7 days for production
            ingestion_rate_mb: 16
            ingestion_burst_size_mb: 32
          storage:
            type: filesystem
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
          schemaConfig:
            configs:
              - from: 2020-10-24
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h

        # Production configuration
        singleBinary:
          replicas: 1
          resources:
            requests:
              cpu: 50m
              memory: 550Mi
            limits:
              cpu: 200m
              memory: 768Mi
          persistence:
            enabled: true
            size: 10Gi
            storageClass: "nfs-logs"

        # Disable distributed components
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0

        gateway:
          enabled: false
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false

        # Sidecar for ruler config (k8s-sidecar)
        sidecar:
          rules:
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 50m
                memory: 64Mi

        monitoring:
          lokiCanary:
            enabled: false

        test:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
