apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/applications/monitoring
    helm:
      values: |
        kube-prometheus-stack:
          grafana:
            podDisruptionBudget:
              maxUnavailable: 1
            ingress:
              enabled: true
              ingressClassName: "nginx"
              hosts:
                - grafana.lab1830.com
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              tls:
                - secretName: grafana-production-tls
                  hosts:
                    - grafana.lab1830.com
            persistence:
              enabled: true
              size: 10Gi
            initChownData:
              enabled: false
            envValueFrom:
              GF_SMTP_PASSWORD:
                secretKeyRef:
                  name: grafana-smtp-secret
                  key: GF_SMTP_PASSWORD
              GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
                secretKeyRef:
                  name: grafana-oauth-secret
                  key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
            env:
              GF_SMTP_ENABLED: "true"
              GF_SMTP_HOST: "smtp.gmail.com:587"
              GF_SMTP_USER: "brian@saturnvsystems.com"
              GF_SMTP_FROM_ADDRESS: "brian@lab1830.com"
              GF_SMTP_FROM_NAME: "Lab1830 Grafana Alerts"
              GF_SMTP_STARTTLS_POLICY: "MandatoryStartTLS"
              GF_SMTP_SKIP_VERIFY: "false"
            resources:
              requests:
                cpu: 25m
                memory: 400Mi
              limits:
                cpu: 100m
                memory: 512Mi
            grafana.ini:
              server:
                root_url: "https://grafana.lab1830.com"
                domain: "lab1830.com"
              auth:
                oauth_auto_login: false
              auth.generic_oauth:
                enabled: true
                allow_sign_up: true
                auto_login: false
                name: Authentik
                client_id: grafana
                scopes: openid profile email
                auth_url: https://auth.lab1830.com/application/o/authorize/
                token_url: https://auth.lab1830.com/application/o/token/
                api_url: https://auth.lab1830.com/application/o/userinfo/
                email_attribute_path: email
                login_attribute_path: preferred_username
                name_attribute_path: name
                role_attribute_path: "contains(groups[*], 'authentik Admins') && 'Admin' || 'Viewer'"
              unified_alerting:
                enabled: true
          prometheus:
            prometheusSpec:
              retention: 15d
              podDisruptionBudget:
                enabled: true
                maxUnavailable: 1
              resources:
                requests:
                  cpu: 200m
                  memory: 1200Mi
                limits:
                  cpu: 1000m
                  memory: 2000Mi
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 50Gi
          alertmanager:
            alertmanagerSpec:
              podDisruptionBudget:
                enabled: true
                maxUnavailable: 1
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
              storage:
                volumeClaimTemplate:
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
              secrets:
                - alertmanager-smtp-secret
            config:
              global:
                resolve_timeout: 5m
                smtp_from: "brian@lab1830.com"
                smtp_smarthost: "smtp.gmail.com:587"
                smtp_auth_username: "brian@saturnvsystems.com"
                smtp_auth_password_file: "/etc/alertmanager/secrets/alertmanager-smtp-secret/smtp-password"
                smtp_require_tls: true
              inhibit_rules:
                - source_matchers:
                    - 'severity = critical'
                  target_matchers:
                    - 'severity =~ warning|info'
                  equal: ['namespace', 'alertname']
                - source_matchers:
                    - 'severity = warning'
                  target_matchers:
                    - 'severity = info'
                  equal: ['namespace', 'alertname']
                - source_matchers:
                    - 'alertname = InfoInhibitor'
                  target_matchers:
                    - 'severity = info'
                  equal: ['namespace']
                - target_matchers:
                    - 'alertname = InfoInhibitor'
              route:
                group_by: ['namespace', 'alertname']
                group_wait: 30s
                group_interval: 5m
                repeat_interval: 4h
                receiver: 'email-brian'
                routes:
                  - receiver: 'null'
                    matchers:
                      - alertname = "Watchdog"
                  - receiver: 'email-brian'
                    matchers:
                      - severity =~ "critical|warning"
                    continue: true
              receivers:
                - name: 'null'
                - name: 'email-brian'
                  email_configs:
                    - to: 'brian@lab1830.com'
                      send_resolved: true
                      headers:
                        subject: '{{ printf "[Lab1830] {{ .Status | toUpper }}: {{ .CommonLabels.alertname }}" }}'
              templates:
                - '/etc/alertmanager/config/*.tmpl'
          kubeStateMetrics:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
          nodeExporter:
            resources:
              requests:
                cpu: 20m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-production
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
