apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/applications/monitoring
    helm:
      values: |
        kube-prometheus-stack:
          grafana:
            ingress:
              enabled: true
              ingressClassName: "nginx"
              hosts:
                - grafana.lab1830.com
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-prod-gitops"
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              tls:
                - secretName: grafana-production-tls
                  hosts:
                    - grafana.lab1830.com
            persistence:
              enabled: true
              size: 10Gi
            initChownData:
              enabled: false
            envFrom:
              - secretRef:
                  name: grafana-smtp-secret
            env:
              GF_SMTP_ENABLED: "true"
              GF_SMTP_HOST: "smtp.gmail.com:587"
              GF_SMTP_FROM_ADDRESS: "blehnen@gmail.com"
              GF_SMTP_FROM_NAME: "Lab1830 Grafana Alerts"
              GF_SMTP_STARTTLS_POLICY: "MandatoryStartTLS"
              GF_SMTP_SKIP_VERIFY: "false"
            grafana.ini:
              server:
                root_url: "https://grafana.lab1830.com"
                domain: "lab1830.com"
              unified_alerting:
                enabled: true
              auth.generic_oauth:
                enabled: true
                name: Authentik
                allow_sign_up: true
                client_id: grafana
                client_secret: 5HukVhR6Cbqbr3UuyIc5VCxaXfuADWpyL3X7KWvDGh6xMPhcKHkUmu0h5u0jnRhMnopYpm00g5sJtIEkmOodhkjCUr3OGUCkHT6OkJLKUjx9A7kX9ZzzJZAMfkOjIdhF
                scopes: openid profile email
                auth_url: https://auth.lab1830.com/application/o/authorize/
                token_url: https://auth.lab1830.com/application/o/token/
                api_url: https://auth.lab1830.com/application/o/userinfo/
                role_attribute_path: contains(groups[*], 'authentik Admins') && 'Admin' || 'Viewer'
                tls_skip_verify_insecure: false
          prometheus:
            prometheusSpec:
              retention: 15d
              resources:
                requests:
                  cpu: 200m
                  memory: 1200Mi
                limits:
                  cpu: 1000m
                  memory: 2000Mi
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 50Gi
          alertmanager:
            alertmanagerSpec:
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
              storage:
                volumeClaimTemplate:
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
          kubeStateMetrics:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
          nodeExporter:
            resources:
              requests:
                cpu: 20m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-production
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
