apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/applications/monitoring
    helm:
      values: |
        grafanaSmtp:
          enabled: true
        kube-prometheus-stack:
          grafana:
            ingress:
              enabled: true
              ingressClassName: "nginx"
              hosts:
                - grafana.lab1830.com
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-prod-gitops"
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              tls:
                - secretName: grafana-production-tls
                  hosts:
                    - grafana.lab1830.com
            persistence:
              enabled: true
              size: 10Gi
            initChownData:
              enabled: false
            smtp:
              enabled: true
              host: "smtp.gmail.com:587"
              skip_verify: false
              from_address: "grafana@lab1830.com"
              from_name: "Lab1830 Grafana Alerts"
            extraSecretMounts:
              - name: smtp-credentials
                secretName: grafana-smtp-secret
                defaultMode: 0440
                mountPath: /etc/secrets/smtp
                readOnly: true
            env:
              GF_SMTP_USER_FILE: "/etc/secrets/smtp/username"
              GF_SMTP_PASSWORD_FILE: "/etc/secrets/smtp/password"
              GF_SMTP_HOST_FILE: "/etc/secrets/smtp/host"
            grafana.ini:
              server:
                root_url: "https://grafana.lab1830.com"
                domain: "lab1830.com"
              smtp:
                enabled: true
                starttls_policy: "OpportunisticStartTLS"
              unified_alerting:
                enabled: true
                error_or_timeout: "alerting"
                nodata_or_nullvalues: "no_data"
                concurrent_render_limit: 5
                evaluation_timeout_seconds: 30
                notification_timeout_seconds: 30
                max_attempts: 3
          prometheus:
            prometheusSpec:
              retention: 15d
              resources:
                requests:
                  cpu: 200m
                  memory: 1200Mi
                limits:
                  cpu: 1000m
                  memory: 2000Mi
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 50Gi
          alertmanager:
            alertmanagerSpec:
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
              storage:
                volumeClaimTemplate:
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
          kubeStateMetrics:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
          nodeExporter:
            resources:
              requests:
                cpu: 20m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-production
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true