apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/infrastructure/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false