apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/applications/vault
    helm:
      valueFiles:
        - values.yaml
      values: |
        # Production-specific overrides
        server:
          ha:
            enabled: true
            replicas: 2
          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: nfs-client
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
        ui:
          enabled: true
          serviceType: ClusterIP
        # Production mode (persistent storage)
        global:
          enabled: true
        injector:
          enabled: true
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true