apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiz-outpost-lite-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/applications/wiz-outpost-lite
    helm:
      values: |
        wiz-outpost-lite:
          agent:
            # Provide credentials directly instead of existingSecret
            clientId: ""  # Will be populated by External Secrets
            clientSecret: ""  # Will be populated by External Secrets
            outpostId: ""  # Will be populated by External Secrets
          
          # Try without custom encryption for now
          encryption:
            create: false
          
          imagePullSecrets:
            - name: wiz-outpost-lite-image-pull
          
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          
          nodeSelector: {}
          tolerations: []
          affinity: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: outpost-lite
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
