apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiz-outpost-lite-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/applications/wiz-outpost-lite
    helm:
      values: |
        wiz-outpost-lite:
          agent:
            secretName: outpost-lite-agent-creds
            outpostRegion: partition-1
          
          # Disable encryption for now since we have the main functionality working
          encryption:
            create: false
          
          # Disable secret creation - we're using External Secrets
          secret:
            create: false
          
          # Use the image pull secret from External Secrets (we'll fix this separately)
          imagePullSecrets:
            - name: wiz-outpost-lite-image-pull
          
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          
          serviceAccount:
            create: false
  destination:
    server: https://kubernetes.default.svc
    namespace: outpost-lite
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
