apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiz-external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/applications/wiz-outpost-lite/templates
    directory:
      recurse: false
      include: "external-secrets.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: outpost-lite
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
