apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiz-outpost-lite-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: main
    path: charts/applications/wiz-outpost-lite
    helm:
      values: |
        wiz-outpost-lite:
          agent:
            secretName: outpost-lite-agent-creds  # This will be created by External Secrets
            # Leave credentials empty - External Secrets will populate them
            clientId: ""
            clientSecret: ""
            outpostId: ""
            outpostRegion: partition-1
          
          # Disable encryption for now
          encryption:
            create: false
            secretName: "wiz-encryption-disabled"
            privateKey: ""
          
          # Disable secret creation - External Secrets will handle it
          secret:
            create: false
          
          imagePullSecrets:
            - name: wiz-outpost-lite-image-pull
          
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          
          serviceAccount:
            create: false
  destination:
    server: https://kubernetes.default.svc
    namespace: outpost-lite
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
