apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiz-production
  namespace: argocd
  labels:
    app.kubernetes.io/name: wiz-connector
    app.kubernetes.io/component: security
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    path: charts/applications/wiz-connector
    targetRevision: main
    helm:
      values: |
        # Production-specific overrides
        vault:
          enabled: false

        wiz-kubernetes-integration:
          global:
            wizApiToken:
              secret:
                create: false
                name: wiz-api-token

          wiz-kubernetes-connector:
            autoCreateConnector:
              clusterFlavor: Kubernetes
              connectorName: "lehnen-lab1830"
            wiz-broker:
              enabled: true
              resources:
                requests:
                  cpu: 100m
                  memory: 200Mi
                limits:
                  cpu: 500m
                  memory: 1Gi

          wiz-sensor:
            sensorClusterName: "lehnen-lab1830"
            diskScan:
              enabled: true
            resources:
              requests:
                cpu: 100m
                memory: 200Mi
              limits:
                cpu: 500m
                memory: 1Gi
            nodeSelector:
              kubernetes.io/os: linux
            tolerations:
              - operator: Exists
            securityContext:
              privileged: false
              allowPrivilegeEscalation: true
              capabilities:
                add:
                  - SYS_ADMIN
                  - SYS_RESOURCE
                  - SYS_PTRACE
                  - NET_ADMIN
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    preference:
                      matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                            - k8s-node1
                            - k8s-node2
                  - weight: 50
                    preference:
                      matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                            - k8s-control
            priorityClassName: "system-cluster-critical"

          wiz-admission-controller:
            enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                cpu: 200m
                memory: 300Mi
            webhook:
              failurePolicy: Fail
              timeoutSeconds: 30

  destination:
    server: https://kubernetes.default.svc
    namespace: wiz

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
