apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: staging
    path: charts/applications/authentik
    helm:
      values: |
        authentik:
          secret_key: "staging-authentik-secret-key-change-me-32chars!"
          
          server:
            replicas: 1
            ingress:
              enabled: true
              ingressClassName: nginx
              hosts:
                - auth-staging.lab1830.com
          
          worker:
            replicas: 1
          
          postgresql:
            enabled: true
          
          redis:
            enabled: true
        
        env:
          AUTHENTIK_BOOTSTRAP_EMAIL: brian@lab1830.com
          AUTHENTIK_BOOTSTRAP_PASSWORD: staging-initial-admin-pw
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
