apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: staging
    path: charts/applications/cert-manager
    helm:
      values: |
        cert-manager:
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi

        clusterIssuers:
          selfsigned:
            enabled: true
            name: selfsigned-clusterissuer-staging

          letsencrypt:
            email: brian@lab1830.com
            staging:
              enabled: true
            production:
              enabled: true
            cloudflare:
              secretName: cloudflare-api-token-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
