apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: staging
    path: charts/applications/homepage
    helm:
      valueFiles:
        - values.yaml
      values: |
        env:
          - name: HOMEPAGE_ALLOWED_HOSTS
            value: "homepage-staging.lab1830.com"
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: homepage-staging.lab1830.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: homepage-staging-tls
              hosts:
                - homepage-staging.lab1830.com
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage-staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
