apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: staging
    path: charts/applications/homepage
    helm:
      valueFiles:
        - values.yaml
      values: |
        ingress:
          hosts:
            - host: homepage-staging.lab1830.com
              paths:
                - path: /
                  pathType: Prefix
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage-staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
