# Update argocd/apps/staging/loki.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.35.1
    helm:
      values: |
        deploymentMode: SingleBinary
        
        loki:
          auth_enabled: false
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: 2020-10-24
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
        
        singleBinary:
          persistence:
            enabled: true
            storageClass: "local-path"
            size: 5Gi
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
        
        read:
          replicas: 0
        backend:
          replicas: 0
        write:
          replicas: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true