apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: staging
    path: charts/infrastructure/storage
    helm:
      values: |
        storageClasses:
          nfsLogs:
            share: /volume1/Logs-Staging  # Different share for staging
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
