apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:brianjlehnen/homelab-gitops.git
    targetRevision: staging
    path: charts/applications/velero
    helm:
      values: |
        # Staging-specific values
        nfsGateway:
          nfs:
            server: "192.168.4.159"
            path: "/volume1/Backups/velero"
        
        velero:
          schedules:
            daily-cluster:
              schedule: "0 2 * * *"  # 2 AM for staging
              template:
                ttl: "72h"  # 3 days retention for staging
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true